images:
- centos-5
- centos-6
- centos-7
- centos-latest
- debian-610
- debian-78
- debian-81
- fedora-20
- fedora-21
- fedora-22
- ubuntu-1004
- ubuntu-1204-20150612
- ubuntu-1204
- ubuntu-1304
- ubuntu-1404-20150320
- ubuntu-1404
- ubuntu-1504
- ubuntu-1510
- ubuntu-latest
